/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'perellano' at '08.02.17 10:17' with Gradle 3.1
 *
 * @author perellano, @date 08.02.17 10:17
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
